# safelist
language: node_js
node_js:
  -â€Š"7"
script:
  - echo "Deploy it in the name of the moon!"
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy - project werockit-conf-website - token $FIREBASE_TOKEN
branches:
  only:
    - master
